// lib/mockProducts.js

const mockProducts = [
  {
    name: "Essential Beige Hoodie",
    price: 499000,
    excerpt: "Soft, breathable hoodie for everyday comfort.",
    category: "men",
    subcategory: "hoodies",
    thumbnail: "https://image.pollinations.ai/prompt/beige%20hoodie%20fashion%20flatlay",
    slug: "essential-beige-hoodie",
  },
  {
    name: "Minimalist Black T-Shirt",
    price: 199000,
    excerpt: "Clean silhouette with premium cotton.",
    category: "men",
    subcategory: "t-shirts",
    thumbnail: "https://image.pollinations.ai/prompt/black%20tshirt%20minimalist%20flatlay",
    slug: "minimalist-black-tshirt",
  },
  {
    name: "Urban Denim Jacket",
    price: 799000,
    excerpt: "Timeless denim jacket for city life.",
    category: "men",
    subcategory: "jackets",
    thumbnail: "https://image.pollinations.ai/prompt/denim%20jacket%20fashion%20flatlay",
    slug: "urban-denim-jacket",
  },
  {
    name: "Streetwear Sneakers",
    price: 899000,
    excerpt: "Durable and stylish street sneakers.",
    category: "men",
    subcategory: "sneakers",
    thumbnail: "https://image.pollinations.ai/prompt/streetwear%20sneakers%20flatlay",
    slug: "streetwear-sneakers",
  },

  // WOMEN
  {
    name: "Classic White Dress",
    price: 699000,
    excerpt: "Elegant, simple and breathable.",
    category: "women",
    subcategory: "dresses",
    thumbnail: "https://image.pollinations.ai/prompt/classic%20white%20dress%20fashion",
    slug: "classic-white-dress",
  },
  {
    name: "Flowy Blouse",
    price: 299000,
    excerpt: "Light and comfortable for daily wear.",
    category: "women",
    subcategory: "blouses",
    thumbnail: "https://image.pollinations.ai/prompt/white%20blouse%20fashion%20minimalist",
    slug: "flowy-blouse",
  },
  {
    name: "Denim Skirt",
    price: 399000,
    excerpt: "Classic denim with modern cut.",
    category: "women",
    subcategory: "skirts",
    thumbnail: "https://image.pollinations.ai/prompt/denim%20skirt%20casual%20fashion",
    slug: "denim-skirt",
  },
  {
    name: "Elegant Nude Heels",
    price: 499000,
    excerpt: "Minimalist high heels for events.",
    category: "women",
    subcategory: "heels",
    thumbnail: "https://image.pollinations.ai/prompt/minimalist%20nude%20heels",
    slug: "elegant-nude-heels",
  },

  // TOPS
  {
    name: "Oversized Sweatshirt",
    price: 399000,
    excerpt: "Comfy oversized daily essential.",
    category: "tops",
    subcategory: "sweatshirts",
    thumbnail: "https://image.pollinations.ai/prompt/oversized%20sweatshirt%20neutral%20fashion",
    slug: "oversized-sweatshirt",
  },
  {
    name: "Casual Crop Top",
    price: 249000,
    excerpt: "Soft fabric and relaxed cut.",
    category: "tops",
    subcategory: "crop-tops",
    thumbnail: "https://image.pollinations.ai/prompt/casual%20crop%20top%20flatlay",
    slug: "casual-crop-top",
  },
  {
    name: "Knitted Tunic",
    price: 599000,
    excerpt: "Warm lightweight tunic.",
    category: "tops",
    subcategory: "tunics",
    thumbnail: "https://image.pollinations.ai/prompt/knitted%20tunic%20soft%20fashion",
    slug: "knitted-tunic",
  },
  {
    name: "Longline T-Shirt",
    price: 299000,
    excerpt: "Minimalist long fit T-shirt.",
    category: "tops",
    subcategory: "t-shirts",
    thumbnail: "https://image.pollinations.ai/prompt/longline%20tshirt%20fashion%20flatlay",
    slug: "longline-tshirt",
  },

  // ACCESSORIES
  {
    name: "Elegant Gold Necklace",
    price: 449000,
    excerpt: "Simple minimalist jewelry piece.",
    category: "accessories",
    subcategory: "jewelry",
    thumbnail: "https://image.pollinations.ai/prompt/minimalist%20gold%20necklace",
    slug: "elegant-gold-necklace",
  },
  {
    name: "Leather Belt",
    price: 299000,
    excerpt: "Soft grain leather with clean buckle.",
    category: "accessories",
    subcategory: "belts",
    thumbnail: "https://image.pollinations.ai/prompt/minimalist%20leather%20belt%20fashion",
    slug: "leather-belt",
  },
  {
    name: "Wool Beanie",
    price: 199000,
    excerpt: "Soft warm everyday beanie.",
    category: "accessories",
    subcategory: "hats",
    thumbnail: "https://image.pollinations.ai/prompt/minimalist%20wool%20beanie",
    slug: "wool-beanie",
  },
  {
    name: "Sunglasses Minimalist",
    price: 599000,
    excerpt: "Stylish lightweight protection.",
    category: "accessories",
    subcategory: "sunglasses",
    thumbnail: "https://image.pollinations.ai/prompt/minimalist%20sunglasses%20fashion",
    slug: "sunglasses-minimalist",
  },

  // EXTRAS
  {
    name: "Everyday Cotton Cap",
    price: 149000,
    excerpt: "Unstructured casual cotton cap.",
    category: "accessories",
    subcategory: "hats",
    thumbnail: "https://image.pollinations.ai/prompt/minimalist%20cotton%20cap%20fashion",
    slug: "everyday-cotton-cap",
  },
  {
    name: "Slimfit Chino Pants",
    price: 499000,
    excerpt: "Tapered silhouette chinos.",
    category: "men",
    subcategory: "pants",
    thumbnail: "https://image.pollinations.ai/prompt/slimfit%20chino%20pants",
    slug: "slimfit-chino-pants",
  },
  {
    name: "Oversized Linen Shirt",
    price: 649000,
    excerpt: "Soft linen, relaxed fit.",
    category: "tops",
    subcategory: "shirts",
    thumbnail: "https://image.pollinations.ai/prompt/linen%20shirt%20flatlay",
    slug: "oversized-linen-shirt",
  },
  {
    name: "Elegant Silver Ring",
    price: 399000,
    excerpt: "Timeless minimalist silver ring.",
    category: "accessories",
    subcategory: "jewelry",
    thumbnail: "https://image.pollinations.ai/prompt/silver%20ring%20minimalist%20fashion",
    slug: "elegant-silver-ring",
  },
];

export default mockProducts;
